# Generated by Django 4.2.16 on 2024-11-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguro', '0003_ciudad_cliente_producto_delete_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, unique=True, verbose_name='Nombres')),
                ('dni', models.CharField(max_length=13, unique=True, verbose_name='RUC o Cédula')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Correo Electrónico')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('phone', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('movil', models.CharField(max_length=15, verbose_name='Celular')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar', verbose_name='Foto del Cliente')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'customer',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='productos',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
