# Generated by Django 4.2.16 on 2024-11-28 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguro', '0004_customer_remove_cliente_ciudad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigencia', models.DateField(verbose_name='Vigencia')),
                ('plazo', models.PositiveIntegerField(verbose_name='Plazo (días)')),
                ('vencimiento', models.DateField(verbose_name='Vencimiento')),
                ('tipo_poliza', models.CharField(max_length=100, verbose_name='Tipo de Póliza')),
                ('valor_asegurado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Asegurado')),
                ('tasa', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa (%)')),
                ('prima_minima', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prima Mínima')),
                ('prima', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prima')),
                ('derecho', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Derecho')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguro.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'cotizacion',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguro.ciudad', verbose_name='Ciudad'),
        ),
    ]
