# Generated by Django 4.2.16 on 2024-11-28 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguro', '0005_ciudad_cotizacion_customer_ciudad'),
    ]

    operations = [
    ]
