# Generated by Django 4.2.16 on 2024-11-29 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguro', '0006_auto_20241128_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'ordering': ['id'], 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelTable(
            name='ciudad',
            table='ciudad',
        ),
    ]
